@startuml
navigationController ^-- delegateAuthorityController
navigationController ^-- appointDepartmentRepController
navigationController ^-- changeCollecitonPointController
class navigationController{
    void:homePage()
}

class ViewStationeryCatalogueView{
}

class RequisitionController{
    void:createViewStationeryCatalogueView()
    void:requestItem(item,qty)
    void:loadMakeStationeryRequestForm()
    void:loadViewStationeryCatalogueView()
    void:deleteRequestedItems()
    void:saveChanges()
    void:submitRequest()
}

class MakeEditStationeryRequestFormView{
}
class ViewPastRequestController{
    void:createSearchRequisitionForm()
    void:loadSearchRequisitionForm(startDate,endDate,approvalStatus)
    void:loadViewStationeryRequestForm(ReqID)
    void:(edit)loadMakeStationeryRequestForm(sameInRequisitonController)
    void:deleteRequisitionForm()
}
class searchRequisitionFormView{

}
class ViewStationeryRequestForm{

}

class approveRequisitionFormController{
    void:createApproveRequisitionFormView()
    void:approveReq(reqID)
    void:rejectReq(reqID)
}

class approveRequisitionFormView{

}


 class delegateAuthorityController{
    void:createDelegateAuthorityView()
    void:confirmDelegation(empID,startDate,endDate)

    void:rescindDelegation(empID)
}

class delegateAuthorityView{

}

class appointDepartmentRepController{
    void:createAppointDepartmentRepView()
    void:confirmDepartmentRep(repID)

}

class appointDepartmentRepView{

}

class changeCollecitonPointController{
    void:confirmChangeCollectionPoint()
}

class changeCollectionPointView{

}
class stationeryRetrievalController{
    void:createStationeryRetrievalFormView()
    void:load
}
class createStationeryRetrievalFormView{

}

class createOrdersController {
    void: homePage()
    void: searchReorderDetailsByCategoryAndDescription(Category category, string searchTerm)
    void: goToOrderQuantity(ReorderItemsForm items)
    void: backToItemCatalogue(ReorderItemsForm items)
    void: goToPlaceOrder(ReorderQuantitiesForm quantities)
    void: backToOrderQuantity(ReorderQuantitiesForm quantities)
    void: submitOrder(ReorderForm reorderForm)
    void: downloadPurchaseOrders(int OrderId)
}

class viewReceivedOrdersList {
    ' serves as back route from Received Orders Details page
    void: viewPastReceivedOrdersList()
    void: viewPastOrder(int orderId)
    void: homePage()
}

class 
@enduml



