@startuml

Class ApprovalStatus <<Entities>> {
+int: ApprovalStatusID
+string: ApprovalStatusName

}

Class Authority <<Entities>> {
+int: AuthorityID
+string: EmployeeID
+DateTime: StartDate
+DateTime: EndDate
}

Class Category <<Entities>> {
+int: CategoryID
+string: CategoryName
}

Class CollectionPoint <<Entities>> {
+int: CollectionPointID
+string: CollectionPointName
}

Class DeliveryStatus <<Entities>> {
+int: DeliveryStatusID
+string: DeliveryStatusName
}

Class Department <<Entities>> {
+string: DepartmentID
+string: DepartmentName
+int: CollectionPointID
+string: DepartmentHead
}

Class DepartmentRepresentative <<Entities>> {
+int: DeptRepID
+string: EmployeeID
+DateTime: StartDate
+DateTime: EndDate
+string: Passcode
}

Class Disbursement <<Entities>> {
+int: DisbursementID
+int: RequisitionID
+DateTime: CollectionDate
+int: CollectedBy
+int: DisbursementDutyID
}

Class DisbursementDetail <<Entities>> {
+int: DisbursementDetailsID
+int: DisbursementID
+int: Quantity
+int: CollectedQty
+string: Reason
+int: RequisitionDetatilsID
}

Class DisbursementDuty <<Entities>> {
+int: DisbursementDutyID
+string: StoreClerkID
+DateTime: DisbursementDate
+bool: isRetrieved
}

Class Employee <<Entities>> {
+string: EmployeeID
+string: DepartmentID
+string: EmployeeName
+string: PhoneNumber
+string: EmailID
+strign: Sex
}

Class InvoiceUploadStatus <<Entities>> {
+int: InvoiceUploadStatusID
+string: InvoiceUploadStatusName
}

Class Item <<Entities>> {
+string: ItemID
+string: ItemName
+string: CategoryID
+string: UnitOfMeasure
}

Class Order <<Entities>> {
+int: OrderID
+DateTime: OrderDate
}

Class OrderSupplier <<Entities>> {
+int: OrderSupplierID
+int: OrderID
+string: SupplierID
+int: DeliveryStatusID
+int: InvoiceUploadStatusID

}

Class OrderSupplierDetail <<Entities>> {
+int: OrderSupplierDetailID
+int: OrderSupplierID
+string: ItemID
+int: Quantity
+decimal: UnitCost
+int: ActualQuantityReceived
}

Class ReorderDetail <<Entities>> {
+string: ItemID
+int: ReorderLevel
+int: ReorderQuantity
+string: ItemName
+int: QtyInStock
}

Class OustandingRequisitionView <<Entities>> {
+int: RequisitionID
+DateTime: ApproveDate
+int: RequisitionDetatilsID
+string: ItemID
+int: OutstandingQuantity
}

Class Requisition <<Entities>> {
+int: RequisitionID
+string: EmployeeID
+DateTime: RequestedDate
+int: AuthorityID
+DateTime: ApproveDate
+int: RetrievalStatusID
+int: ApprovalStatusID
}

Class RequisitionDetail <<Entities>> {
+int: RequisitionDetatilsID
+int: RequisitionID
+string: ItemID
+int: Quantity
}

Class RetrievalItem <<Entities>> {
+string: ItemID
+int: QtyToRetrieve
+int: QtyInStock
}

Class RetrievalStatus <<Entities>> {
+int: RetrievalStatusID
+string: RetrievalStatusName
}

Class StockCountItem <<Entities>> {
+string: ItemID
+string: ItemName
+string: UnitOfMeasure
+int: QtyInStock
}

Class StockTransaction <<Entities>> {
+int: TransactionID
+string: ItemID
+string: Description
+int: Adjustment
+string: EmployeeID
}

Class StockVoucher <<Entities>> {
+int: DiscrepancyID
+string: ItemID
+int: OriginalCount
+int: ActualCount
+decimal: ItemCost
+string: Reason
+string: RaisedBy
+string: ApprovedBy
+DateTime: RaisedByDate
+DateTime: ApprovedDate
}

Class Supplier <<Entities>> {
+string: SupplierID
+string: SupplierName
+string: ContactName
+string: PhoneNumber
+string: FaxNumber
+string: Address
}

Class SupplierItem <<Entities>> {
+int: SupplierItemID
+string: SupplierID
+string: ItemID
+int: Rank
+decimal: Cost
}

Class Requester <<Entities>> {

}
@enduml

@startuml
ClassDepartment o-- ClassEmployee : has
ClassDepartment o-- ClassCollectionPoint : has
ClassEmployee o-- ClassAuthority : contains
ClassEmployee o-- CalssDepartmentRepresentative : has
ClassEmployee o-- ClassRequisition : request
ClassRequisition --o ClassApprovalStatus : has
ClassRequisition --o ClassRetrievalStatus : has
ClassRequisition o-- ClassRequisitionDetail : contains
ClassDisburesement o-- ClassRequisition
ClassDisburesement o-- ClassDisburesementDuty
ClassDisburesement o-- ClassDisburesementDetails
ClassOrder o-- ClassOrderSupplier
ClassSupplier o-- ClassOrderSupplier : contains
ClassSupplier o-- ClassSupplierItem
ClassOrderSupplier o-- ClassOrderSupplierDetail
ClassOrderSupplier o-- ClassDeliveryStatus
classCategory o-- ClassItems : contains
ClassItems o-- ClassStockTransaction : 
ClassItems o-- ClassOrderSupplierDetail
ClassItems o-- ClassRequisitionDetail


@enduml