@startuml
actor StoreClerk
boundary RestockInventoryActivity
control OrderAPI
Participant OrderService

StoreClerk->RestockInventoryActivity: 1.SelectOrderIDAndSupplier
activate RestockInventoryActivity
StoreClerk->RestockInventoryActivity: 2.Search()
RestockInventoryActivity->OrderAPI: 3.GetOrderDetailsofOrderAndSupplier()
activate OrderAPI
OrderAPI->OrderService: 4.GetOrderDetailsofOrderAndSupplier()
activate OrderService
deactivate OrderService
deactivate OrderAPI
StoreClerk->RestockInventoryActivity: 6.ADD()
note right:Dialog box will appear to add quantity
StoreClerk->RestockInventoryActivity: 7.AddQuantity()
StoreClerk->RestockInventoryActivity: 8. OK()
RestockInventoryActivity->OrderAPI: 9.AddStock()
activate OrderAPI
OrderAPI->OrderService: 10.UpdateQuantityReceived()
activate OrderService
deactivate OrderAPI


@enduml