@startuml

'' Requisition
' Store Clerk and Store Supervisor
class stationeryRetrievalApiController <<ApiController>> {
    ' GET /api/retrievalItems
    List<RetrievalItem>: getRetrievalItems()
    ' POST /api/raiseStockVoucher
    void: raiseStockVoucher(int itemId, int adjustment, string reason)
    ' POST /api/submitRetrievalForm/{storeClerkId}
    void: submitRetrievalForm()
}

''Store clerk and store supervisor
class monthlyInventoryController<<ApiController>>{
    ' GET /api/
}
@enduml